// Scripted journeys run identically against the legacy app and the React build (see run.mjs).
// A step is { do: 'hash' | 'click' | 'fill' | 'type' | 'press' | 'select' | 'files' | 'scroll' | 'wait' | 'snap', … }.
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const FIXTURE = path.join(path.dirname(fileURLToPath(import.meta.url)), 'fixtures', 'foto.png');

const named = (desc, fn) => Object.assign(fn, { desc });
const go = (to) => ({ do: 'hash', to });
const snap = (name, extra = {}) => ({ do: 'snap', name, ...extra });
const click = (target, extra = {}) => ({ do: 'click', target, desc: target.desc, ...extra });
const fill = (target, value, extra = {}) => ({ do: 'fill', target, value, desc: target.desc, ...extra });
const wait = (ms) => ({ do: 'wait', ms });
const press = (key, extra = {}) => ({ do: 'press', key, ...extra });
const select = (target, value) => ({ do: 'select', target, value, desc: target.desc });

const button = (name, exact = true) => named(`button "${name}"`, (p) => p.getByRole('button', { name, exact }).first());
// A button inside the screen (not the desktop navigation, whose "Publicar vaga" tab shares the name).
const mainButton = (name) =>
  named(`main button "${name}"`, (p) => p.locator('main').getByRole('button', { name, exact: true }).first());
const label = (name) => named(`label "${name}"`, (p) => p.getByLabel(name, { exact: true }).first());
const placeholder = (text) => named(`placeholder "${text}"`, (p) => p.getByPlaceholder(text, { exact: true }).first());
const visible = (css) => named(css, (p) => p.locator(css).locator('visible=true').first());

const loginAs = (role) => [
  go('/login'),
  click(button(role === 'recrutador' ? 'Recrutador' : 'Trabalhador')),
  click(button('Entrar')),
  wait(700)
];

const snapRoutes = (routes) => routes.flatMap((r) => [go(r), snap(r)]);

const COMMON_ROUTES = [
  '/splash',
  '/login',
  '/escolha-perfil',
  '/cadastro/trabalhador',
  '/cadastro/recrutador',
  '/verificar-email',
  '/completar-perfil/trabalhador',
  '/completar-perfil/recrutador',
  '/esqueci-senha',
  '/redefinir-senha',
  '/mural',
  '/vaga/BC-4821',
  '/vaga/BC-4822',
  '/vaga/BC-5014',
  '/vaga/BC-4830',
  '/vaga/XXX',
  '/confirmar/BC-4855',
  '/enviado/BC-4855',
  '/minhas-candidaturas',
  '/vagas-salvas',
  '/selecionado/BC-4712',
  '/selecionado/BC-4821',
  '/avaliar/BC-4703',
  '/perfil',
  '/perfil/editar',
  '/trabalhador/edson',
  '/trabalhador/silas',
  '/trabalhador/edson/BC-4821',
  '/empresa',
  '/empresa/editar',
  '/construtora/alvorada',
  '/construtora/belem',
  '/construtora/nao-existe',
  '/avaliacoes/construtora/meridiano',
  '/avaliacoes/construtora/belem',
  '/avaliacoes/trabalhador/jorge',
  '/avaliacoes/trabalhador/silas',
  '/notificacoes',
  '/configuracoes',
  '/configuracoes/privacidade',
  '/criar-vaga',
  '/vaga-publicada/BC-4821',
  '/vaga-gerenciar/BC-4822',
  '/vaga-gerenciar/BC-4821',
  '/vaga-gerenciar/BC-4998',
  '/vaga-gerenciar/BC-4960',
  '/fechado/BC-4821',
  '/fechado/BC-4998',
  '/impulsionar/BC-4821',
  '/historico',
  '/rota-que-nao-existe'
];

export const SCENARIOS = [
  { name: 'rotas-trabalhador', start: '#/splash', steps: snapRoutes(COMMON_ROUTES) },
  { name: 'rotas-recrutador', start: '#/splash', steps: [...loginAs('recrutador'), ...snapRoutes(COMMON_ROUTES)] },
  { name: 'raiz-redireciona', start: '', steps: [snap('raiz')] },
  {
    name: 'link-direto',
    start: '#/vaga/BC-4841',
    steps: [snap('deep-link'), click(button('Voltar')), snap('voltar-fallback')]
  },

  {
    name: 'cadastro-trabalhador',
    start: '#/splash',
    steps: [
      click(button('Criar minha conta')),
      snap('escolha'),
      click(button('Continuar')),
      snap('passo-nome'),
      click(button('Continuar')),
      snap('erro-vazio'),
      fill(label('Nome completo'), 'Jorge'),
      click(button('Continuar')),
      snap('erro-sobrenome'),
      fill(label('Nome completo'), 'Jorge Mendes'),
      click(button('Continuar')),
      snap('passo-cpf'),
      { do: 'type', target: label('CPF'), value: '1234567890' },
      snap('cpf-mascara-parcial'),
      click(button('Continuar')),
      snap('erro-cpf'),
      { do: 'type', target: label('CPF'), value: '19' },
      snap('cpf-completo'),
      click(button('Continuar')),
      fill(label('E-mail'), 'jorge@'),
      click(button('Continuar')),
      snap('erro-email'),
      fill(label('E-mail'), 'jorge@email.com'),
      click(button('Continuar')),
      snap('passo-senha'),
      fill(label('Senha'), 'abc'),
      click(button('Criar minha conta')),
      snap('erro-senha-curta'),
      fill(label('Senha'), 'abcdefgh'),
      click(button('Criar minha conta')),
      snap('erro-senha-numeros'),
      fill(label('Senha'), 'abcdefgh1'),
      snap('forca-media'),
      fill(label('Senha'), 'abcdefgh1!'),
      snap('forca-forte'),
      fill(label('Confirme a senha'), 'outra'),
      click(button('Criar minha conta')),
      snap('erro-confirmacao'),
      click(button('Mostrar senha')),
      snap('senha-visivel'),
      fill(label('Confirme a senha'), 'abcdefgh1!'),
      click(button('Criar minha conta')),
      snap('erro-aceite'),
      click((p) => p.getByText('Li e aceito as condições de uso da Bicos')),
      click(button('Criar minha conta')),
      snap('enviando'),
      wait(900),
      snap('verificar-email'),
      click(button('Abrir meu e-mail')),
      snap('completar-1'),
      click(button('Continuar')),
      snap('erro-cargo'),
      select(label('Cargo ou especialidade principal'), 'Pintor'),
      click(button('Continuar')),
      snap('completar-2'),
      click(button('Concluir perfil')),
      snap('erros-regiao-especialidade'),
      select(label('Região de atuação'), 'Mooca, SP'),
      click(button('Reboco')),
      click(button('Pintura')),
      click(button('Reboco')),
      snap('especialidades'),
      click(button('Voltar')),
      snap('voltou-passo-1'),
      click(button('Continuar')),
      click(button('Concluir perfil')),
      wait(200),
      snap('mural')
    ]
  },
  {
    // With animations on: state changes apply instantly (no CSS transition), as in the legacy app.
    name: 'microinteracoes',
    motion: true,
    viewports: ['phone'],
    start: '#/cadastro/trabalhador',
    steps: [
      fill(label('Nome completo'), 'Ana Souza'),
      click(button('Continuar'), { after: 0 }),
      snap('barra-de-progresso-sem-transicao'),
      { do: 'type', target: label('CPF'), value: '12345678901' },
      click(button('Continuar')),
      fill(label('E-mail'), 'ana@x.com'),
      click(button('Continuar')),
      fill(label('Senha'), 'abcdefgh1'),
      { do: 'mouse', x: 5, y: 5 },
      click((p) => p.getByText('Li e aceito as condições de uso da Bicos'), { after: 0 }),
      snap('checkbox-sem-transicao')
    ]
  },
  {
    // Editing in the middle of a masked field keeps the caret where the legacy app kept it.
    name: 'mascara-cursor',
    start: '#/cadastro/trabalhador',
    steps: [
      fill(label('Nome completo'), 'Ana Souza'),
      click(button('Continuar')),
      { do: 'type', target: label('CPF'), value: '12345678' },
      press('Home'),
      press('ArrowRight'),
      press('ArrowRight'),
      press('ArrowRight'),
      press('ArrowRight'),
      press('9'),
      snap('digito-no-meio'),
      press('Backspace'),
      press('Backspace'),
      snap('apagou-no-meio'),
      press('End'),
      press('x'),
      snap('letra-ignorada')
    ]
  },
  {
    name: 'cadastro-recrutador-cnpj-existente',
    start: '#/escolha-perfil',
    steps: [
      click((p) => p.getByText('Quero contratar')),
      snap('escolha-recrutador'),
      click(button('Continuar')),
      fill(label('Nome da empresa'), 'Ab'),
      click(button('Continuar')),
      snap('erro-razao'),
      fill(label('Nome da empresa'), 'Obra Nova'),
      click(button('Continuar')),
      { do: 'type', target: label('CNPJ'), value: '11111111111111' },
      snap('cnpj-mascara'),
      click(button('Continuar')),
      fill(label('E-mail'), 'obra@nova.com'),
      click(button('Continuar')),
      fill(label('Senha'), 'senha1234'),
      fill(label('Confirme a senha'), 'senha1234'),
      click((p) => p.getByText('Li e aceito as condições de uso da Bicos')),
      click(button('Criar minha conta')),
      wait(900),
      snap('erro-cnpj-existente'),
      fill(label('CNPJ'), '12345678000199'),
      snap('erro-limpo'),
      click(button('Voltar')),
      click(button('Voltar')),
      snap('voltou-inicio'),
      click(button('Voltar')),
      snap('voltou-escolha')
    ]
  },
  {
    name: 'login-recuperar-senha',
    start: '#/login',
    steps: [
      fill(label('E-mail, CPF ou CNPJ'), 'jorge@email.com'),
      fill(label('Senha'), 'minhasenha'),
      click(button('Mostrar senha')),
      snap('login-preenchido'),
      click(button('Esqueci minha senha')),
      click(button('Enviar link')),
      snap('erro-email'),
      fill(label('E-mail'), 'jorge@email.com'),
      click(button('Enviar link')),
      snap('enviando'),
      wait(800),
      snap('link-enviado'),
      click(button('Já abri o link')),
      click(button('Salvar nova senha')),
      snap('erro-curta'),
      fill(label('Senha'), 'nova12345'),
      fill(label('Confirme a senha nova'), 'nova1234'),
      click(button('Salvar nova senha')),
      snap('erro-diferentes'),
      fill(label('Confirme a senha nova'), 'nova12345'),
      click(button('Salvar nova senha')),
      wait(800),
      snap('senha-redefinida'),
      click(button('Ir para o login')),
      snap('login-de-novo'),
      click(button('Continuar com o Google')),
      snap('google-carregando'),
      wait(1500),
      snap('mural')
    ]
  },
  {
    name: 'mural-busca-filtros',
    start: '#/splash',
    steps: [
      go('/mural'),
      snap('mural'),
      fill(visible('input[type="search"]'), 'pint'),
      snap('busca-pint'),
      fill(visible('input[type="search"]'), 'meridiano'),
      snap('busca-meridiano'),
      fill(visible('input[type="search"]'), 'zzzz'),
      snap('sem-resultado'),
      click(button('Limpar busca')),
      snap('busca-limpa'),
      click(visible('button:has-text("Filtros")')),
      snap('filtros-aberto', { viewportOnly: true }),
      click(button('Pintor')),
      click(button('Até 5 km')),
      click(button('Hoje')),
      click((p) => p.getByText('Avisar quando aparecer bico novo')),
      snap('filtros-marcados', { viewportOnly: true }),
      click(button('Escolher', false)),
      snap('cidades', { viewportOnly: true }),
      fill(placeholder('Digite o nome da cidade'), 'sao jose'),
      snap('cidades-busca', { viewportOnly: true }),
      fill(placeholder('Digite o nome da cidade'), 'xyzxyz'),
      snap('cidades-nenhuma', { viewportOnly: true }),
      fill(placeholder('Digite o nome da cidade'), 'campinas'),
      click((p) => p.getByRole('option').first()),
      snap('cidade-escolhida', { viewportOnly: true }),
      click(button('Fechar')),
      snap('mural-campinas'),
      click(visible('button:has-text("Ver bicos em São Paulo")')),
      snap('volta-sp'),
      click(visible('button:has-text("Filtros")')),
      click(button('Limpar')),
      // Sorting: a Tag in the filter sheet on tablet/desktop, a segmented control on the phone mural.
      click(button('Maior valor'), { only: ['tablet', 'desktop'] }),
      click((p) => p.getByRole('button', { name: /^Ver \d+ vagas?$/ })),
      click(button('Maior valor'), { only: ['phone'] }),
      snap('ordenado-valor'),
      click(visible('button:has-text("Filtros")'), { only: ['tablet', 'desktop'] }),
      click(button('Mais cedo')),
      click((p) => p.getByRole('button', { name: /^Ver \d+ vagas?$/ }), { only: ['tablet', 'desktop'] }),
      snap('ordenado-cedo')
    ]
  },
  {
    name: 'mural-salvar-carrossel',
    start: '#/mural',
    steps: [
      click(button('Salvar vaga')),
      snap('salvou'),
      click(button('Remover dos salvos')),
      snap('removeu'),
      go('/vaga/BC-4821'),
      click(button('Próxima foto')),
      wait(1500),
      snap('foto-2'),
      { do: 'eval', fn: () => document.querySelector('[aria-roledescription="carrossel"]').focus() },
      press('ArrowRight'),
      wait(700),
      snap('foto-3-teclado'),
      go('/mural'),
      wait(300),
      snap('tile-na-foto-3'),
      go('/vagas-salvas'),
      snap('salvas'),
      click(button('Remover dos salvos')),
      snap('salvas-removeu')
    ]
  },
  {
    name: 'candidatura',
    start: '#/vaga/BC-4855',
    steps: [
      click(visible('button:has-text("Quero esse bico")')),
      snap('confirmar'),
      click(button('Sim, quero esse bico')),
      snap('enviando'),
      wait(800),
      snap('enviado'),
      click(button('Ver minhas candidaturas')),
      snap('minhas'),
      go('/vaga/BC-4855'),
      snap('vaga-com-candidatura'),
      click(visible('button:has-text("Cancelar candidatura")')),
      snap('dialogo-cancelar', { viewportOnly: true }),
      click((p) => p.getByRole('button', { name: 'Voltar', exact: true }).last()),
      snap('dialogo-fechado'),
      click(visible('button:has-text("Cancelar candidatura")')),
      click((p) => p.getByRole('button', { name: 'Cancelar candidatura', exact: true }).last()),
      wait(200),
      snap('cancelada')
    ]
  },
  {
    name: 'avaliar-diaria',
    start: '#/minhas-candidaturas',
    steps: [
      click((p) => p.getByRole('link', { name: /Servente de obra, Diária concluída/ })),
      snap('avaliar'),
      click((p) => p.locator('.icon.cursor-pointer').nth(2)),
      click(button('EPI no local')),
      click(button('Pagou no dia')),
      fill(label('Quer escrever algo? (opcional)'), 'Tudo certo'),
      snap('preenchido'),
      click(button('Enviar avaliação')),
      snap('minhas-depois')
    ]
  },
  {
    name: 'perfil-trabalhador-posts',
    start: '#/perfil',
    steps: [
      click(button('Publicar')),
      snap('composer', { viewportOnly: true }),
      { do: 'files', target: (p) => p.locator('input[type="file"]').first(), files: FIXTURE },
      fill(label('Descrição'), 'Muro novo'),
      snap('composer-com-foto', { viewportOnly: true }),
      click((p) => p.getByRole('button', { name: 'Publicar', exact: true }).last()),
      snap('post-publicado'),
      click((p) => p.getByRole('button', { name: 'Excluir post' }).first()),
      snap('dialogo-excluir', { viewportOnly: true }),
      click((p) => p.getByRole('button', { name: 'Excluir post', exact: true }).last()),
      snap('post-excluido'),
      click(button('Editar')),
      fill(label('Nome completo'), 'Jorge Mendes Silva'),
      click(button('Pintura')),
      snap('editar'),
      click(button('Salvar alterações')),
      snap('perfil-salvo'),
      go('/configuracoes'),
      snap('configuracoes'),
      click(button('Privacidade e dados', false)),
      click(button('Exportar meus dados')),
      snap('exportando'),
      wait(1100),
      snap('exportado'),
      click(button('Excluir minha conta')),
      snap('dialogo-conta', { viewportOnly: true }),
      click(button('Cancelar')),
      snap('dialogo-fechado')
    ]
  },
  {
    name: 'recrutador-aprovar',
    start: '#/splash',
    steps: [
      ...loginAs('recrutador'),
      snap('mural-recrutador'),
      go('/vaga-gerenciar/BC-4998'),
      snap('gerenciar'),
      click(button('Recusar candidato')),
      snap('recusou'),
      click((p) => p.getByText('Bruno Tavares')),
      snap('perfil-candidato'),
      click(button('Aprovar para a vaga · 1 de 2')),
      snap('aprovou-um'),
      click((p) => p.getByText('Bruno Tavares')),
      snap('candidato-aprovado'),
      click(button('Desfazer')),
      snap('desfeito'),
      click(button('Voltar')),
      click(button('Aprovar candidato')),
      snap('aprovou-direto'),
      click(button('Aprovar candidato')),
      snap('fechado'),
      go('/vaga-gerenciar/BC-4998'),
      snap('gerenciar-fechado'),
      go('/mural'),
      snap('mural-sem-vaga')
    ]
  },
  {
    name: 'recrutador-publicar',
    start: '#/splash',
    steps: [
      ...loginAs('recrutador'),
      go('/criar-vaga'),
      click(button('Continuar')),
      snap('erros-passo-1'),
      fill(label('Tipo de serviço'), 'Pedreiro'),
      fill(label('Endereço da obra'), 'Rua A, 10'),
      click((p) => p.getByRole('radio', { name: /^No fim de semana/ })),
      fill(placeholder('7'), '8x'),
      snap('horario-parcial'),
      click(button('Continuar')),
      snap('erro-horario'),
      fill(placeholder('17'), '16'),
      fill(label('Diárias'), ''),
      click(button('Continuar')),
      snap('erro-diarias'),
      fill(label('Diárias'), '3'),
      fill(label('Data (opcional)'), '12 out'),
      { do: 'files', target: (p) => p.locator('input[type="file"]').first(), files: FIXTURE },
      snap('passo-1-completo'),
      click(button('Continuar')),
      snap('passo-2'),
      click(mainButton('Publicar vaga')),
      snap('erros-passo-2'),
      fill(label('Valor da diária'), '50'),
      click(mainButton('Publicar vaga')),
      snap('erro-valor-minimo'),
      click(button('Deixar valor a combinar')),
      snap('a-combinar'),
      click(button('Definir um valor')),
      fill(label('Valor da diária'), '250'),
      click(button('Ferramenta própria')),
      fill(label('Descrição do bico'), 'Assentar blocos.'),
      snap('passo-2-completo'),
      click(button('Voltar')),
      snap('voltou-passo-1'),
      click(button('Continuar')),
      click(mainButton('Publicar vaga')),
      snap('publicando'),
      wait(900),
      snap('publicada'),
      click(button('Impulsionar essa vaga')),
      click(button('24h + aviso por WhatsApp', false)),
      snap('impulsionar'),
      click(button('Impulsionar por R$ 39')),
      snap('gerenciar-nova'),
      click(visible('button:has-text("Encerrar vaga")')),
      snap('dialogo-encerrar', { viewportOnly: true }),
      click((p) => p.getByRole('button', { name: 'Encerrar vaga', exact: true }).last()),
      snap('mural-apos-encerrar'),
      go('/historico'),
      snap('historico')
    ]
  },
  {
    name: 'recrutador-empresa',
    start: '#/splash',
    steps: [
      ...loginAs('recrutador'),
      go('/empresa'),
      click((p) => p.getByRole('button', { name: 'Excluir post' }).first()),
      snap('dialogo-excluir', { viewportOnly: true }),
      click(button('Cancelar')),
      click((p) => p.getByRole('button', { name: 'Excluir post' }).first()),
      click((p) => p.getByRole('button', { name: 'Excluir post', exact: true }).last()),
      snap('post-excluido'),
      click(button('Editar')),
      fill(label('Nome da empresa'), 'Meridiano Obras'),
      select(label('Tipo de obra'), 'Comercial'),
      { do: 'files', target: (p) => p.locator('input[type="file"]').nth(1), files: FIXTURE },
      snap('editar-empresa'),
      click(button('Salvar alterações')),
      snap('empresa-salva'),
      go('/vaga-gerenciar/BC-4821'),
      click(button('Aprovar candidato')),
      click(button('Aprovar candidato')),
      snap('dois-aprovados'),
      click(button('Aprovar candidato')),
      wait(200),
      snap('equipe-fechada')
    ]
  },
  {
    name: 'menu-conta-desktop',
    viewports: ['tablet', 'desktop'],
    start: '#/mural',
    steps: [
      click(button('Menu da conta')),
      snap('menu-aberto', { viewportOnly: true }),
      press('Escape'),
      snap('menu-fechado', { viewportOnly: true }),
      click(button('Menu da conta')),
      click((p) => p.getByRole('menuitem', { name: 'Vagas salvas' })),
      snap('vagas-salvas'),
      click(button('Menu da conta')),
      click((p) => p.getByRole('menuitem', { name: 'Sair da conta' })),
      snap('saiu')
    ]
  },
  {
    name: 'navegacao-abas',
    start: '#/mural',
    steps: [
      { do: 'scroll', y: 600 },
      snap('mural-rolado', { viewportOnly: true }),
      click((p) =>
        p
          .getByRole('button', { name: /^(Minhas|Candidaturas)$/ })
          .locator('visible=true')
          .first()
      ),
      snap('minhas'),
      click((p) => p.getByRole('button', { name: 'Perfil', exact: true }).locator('visible=true').first()),
      snap('perfil'),
      click((p) =>
        p
          .getByRole('button', { name: /^Vagas$/ })
          .locator('visible=true')
          .first()
      ),
      snap('mural-de-novo', { viewportOnly: true })
    ]
  },
  {
    name: 'gps-cidade',
    geolocation: { latitude: -22.9, longitude: -47.06 },
    start: '#/mural',
    steps: [
      click(visible('button:has-text("Filtros")')),
      click(button('Escolher', false)),
      click(button('Usar minha localização')),
      wait(600),
      snap('cidade-gps', { viewportOnly: true })
    ]
  }
];
