// Reads icons/*.svg (vendored from lucide-static) and writes js/utils/iconData.js as a
// name -> data:URI map. The icon mask-image then never depends on an external file
// fetch, which the browser's CORS policy blocks when the app is opened directly via
// file:// (unlike a plain <img src>, which is unaffected).
const fs = require('fs');
const path = require('path');

const iconsDir = path.join(__dirname, '..', 'icons');
const outFile = path.join(__dirname, '..', 'js', 'utils', 'iconData.js');

const files = fs.readdirSync(iconsDir).filter((f) => f.endsWith('.svg')).sort();
const entries = files.map((f) => {
  const name = f.replace(/\.svg$/, '');
  const svg = fs.readFileSync(path.join(iconsDir, f), 'utf8').trim();
  const encoded = encodeURIComponent(svg).replace(/'/g, '%27').replace(/"/g, '%22');
  return `  '${name}': 'data:image/svg+xml,${encoded}'`;
});

const content = `// AUTO-GENERATED by scripts/gen-icons.cjs from icons/*.svg — do not edit by hand.\n` +
  `export const ICON_DATA = {\n${entries.join(',\n')}\n};\n`;

fs.writeFileSync(outFile, content);
console.log(`wrote ${outFile} with ${files.length} icons`);
